List<String> TagList = [
  'Vivienda (Alquiler/Hipoteca)',
  'Comida (Supermercado)',
  'Ocio y Entretenimiento',
  'Restaurantes y Bares',
  'Servicios del Hogar (Agua, Luz, Gas, Internet)',
  'Transporte (Combustible, Mantenimiento Vehículo, Transporte Público)',
  'Salud (Médico, Farmacia, Seguro)',
  'Educación (Cursos, Libros, Matrículas)',
  'Ropa y Calzado',
  'Cuidado Personal (Peluquería, Cosméticos)',
  'Mascotas',
  'Viajes y Vacaciones',
  'Regalos y Celebraciones',
  'Mobiliario y Decoración',
  'Reparaciones y Mejoras del Hogar',
  'Electrónica y Electrodomésticos',
  'Deudas y Préstamos',
  'Impuestos y Tasas',
  'Seguros (no de salud ni vehículo)',
  'Deportes y Actividades Físicas',
  'Suscripciones (Streaming, Apps, Gimnasio)',
  'Cultura (Libros, Revistas, Museos)',
  'Tecnología y Software',
  'Imprevistos',
  'Ahorro e Inversión',
  'Desarrollo Profesional (Cursos, Talleres)',
  'Hijos/Familiares (Gastos específicos)',
  'Donaciones y Caridad',
  'Otros Gastos Misceláneos',
];
