name: cuentas_android
description: "Aplicacion de gestion de gastos"

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 5.0.0
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  cloud_firestore: ^5.4.0
  dart_format: ^1.1.17
  file_picker: ^8.1.5
  firebase_auth: ^5.2.0
  firebase_core: ^3.4.0
  fl_chart: ^0.69.0
  flutter:
    sdk: flutter
  flutter_colorpicker: ^1.1.0
  flutter_launcher_icons: ^0.14.1
  flutter_svg: ^2.0.10+1
  fluttertoast: ^8.2.4
  font_awesome_flutter: ^10.7.0
  get: ^4.6.6
  google_fonts: ^6.2.1
  gson: ^0.1.4
  html: ^0.15.4
  http: ^1.2.2
  image_picker: ^1.1.2
  multi_select_flutter: ^4.1.3
  path_provider: ^2.1.2
  path_provider_windows: ^2.2.0
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - lib/assets/images/
    - lib/assets/images/logo.png
    - lib/assets/images/logo.svg
    - lib/assets/images/nuevo.png
    - lib/assets/images/loading.gif
    - lib/assets/images/background/
    - lib/assets/images/background/dia1.jpeg
    - lib/assets/images/background/dia2.jpeg
    - lib/assets/images/background/tarde1.jpeg
    - lib/assets/images/background/tarde2.jpeg
    - lib/assets/images/background/noche1.jpeg
    - lib/assets/images/background/noche2.jpeg
